# Generated by Django 3.1.3 on 2021-04-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0005_auto_20210416_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='content',
        ),
    ]
