# Generated by Django 3.1.3 on 2021-04-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0006_auto_20210416_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='chocies',
            new_name='choices',
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.IntegerField(default=1),
        ),
    ]
